version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: farofa-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: farofa-championship
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: